nnoremap <silent> ,b :bprevious<CR>
nnoremap <silent> -b :bnext<CR>
nnoremap <silent> ,B :bfirst<CR>
nnoremap <silent> -B :blast<CR>
nnoremap <silent> ,c :cprev<CR>
nnoremap <silent> ,cc :cclose<CR>
nnoremap <silent> -c :cnext<CR>
nnoremap <silent> ,C :cfirst<CR>
nnoremap <silent> -C :clast<CR>
